### PR TITLE
[TS] Add onCancel to ConfirmationAlertOptions

### PR DESCRIPTION
**Pull request by nexpid**
exactly what the title says <:bleh:1062093991157436466>

### CODE REVIEW

**Comment by blank85** [comment]
What do you mean?

**Comment by Gabe616** [comment]
???

**Comment by blank85** [comment]
What do you mean by OnCancel

**Comment by Gabe616** [comment]
dawg i just added an onCancel function to the ConfirmationAlertOptions interface in typings

**Pull request merged**
