### PR TITLE
[Utils] Implement timeout for safeFetch

### PR DESCRIPTION
**Pull request by amsryq**

### CODE REVIEW

**Comment by yellowsink** [comment]
I'm maybe not testing it right, but these requests are definitely taking longer than 100ms to resolve: (see images)

image
image

**Comment by yellowsink** [comment]
I threw together a server that takes 5 seconds to respond
image,
image

and i'm pretty sure this doesn't work consistently, despite the fact that it has aborted it a couple of times somehow.

again, i may be using it wrong though

**Comment by amsryq** [comment]
@yellowsink it's supposed to be the 3rd argument

**Comment by yellowsink** [comment]
Oh right I'm blind lol

Clearly more coffee required ;)

**Comment by yellowsink** [comment]
apologies for the brain failure on my end, looks good to me :+1:  :)
image

**Review by yellowsink — APPROVED** [review]

**Pull request merged**
