### PR TITLE
[TS] Fix definitions from "cleanup"

### PR DESCRIPTION
**Pull request by redstonekasi**

### CODE REVIEW

**Comment by jackmthws** [comment]
Doesn't this break using the enum values

**Comment by redstonekasi** [comment]
No it's a definition file.

**Comment by jackmthws** [comment]
Pretty sure it does

**Comment by maisymoe** [comment]
This was an intentional change - rollup would explode when using the enum values with `declare` rather than `export`. Does it cause problems?

**Comment by redstonekasi** [comment]
Well of course it explodes, let me fix that real quick.

**Comment by redstonekasi** [comment]
You are not supposed to import from definition files is the issue btw.

**Comment by redstonekasi** [comment]
Actually ugh there's still something that makes this not a definition file.

**Comment by maisymoe** [comment]
> Actually ugh there's still something that makes this not a definition file.
> 

Does this cause an issue with the typegen, or something?

**Comment by redstonekasi** [comment]
It'll be easier to simply adjust `treetype-ts` to accomodate this issue. So I'll close the PR.

**Pull request closed without merging**
